name:  Deploy Java Coder Template

env:
  BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  deploy-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest commit hash
        id: latest_commit
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get commit title
        id: commit_title
        run: echo "title=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

      # - name: Update Coder Template
      #   uses: matifali/update-coder-template@v3
      #   with:
      #     id: java
      #     dir: java
      #     url: https://coder.iztec.dev
      #     name: ${{ steps.latest_commit.outputs.hash }}
      #     message: ${{ steps.commit_title.outputs.title }}
      #     coder_session_token: ${{ secrets.CODER_SESSION_TOKEN }}
    
      - name: Show value
        run: |
          echo "-----------------"
          echo "${BWS_ACCESS_TOKEN}"
          echo "-----------------"
          echo "access_token = ${BWS_ACCESS_TOKEN}\n" > ubuntu/terraform.tfvars
          ls 
          cat ubuntu/terraform.tfvars
    
      - name: Update Coder Template ubuntu
        uses: matifali/update-coder-template@v3
        with:
          id: ubuntu
          dir: ubuntu
          url: https://coder.iztec.dev
          name: ${{ steps.latest_commit.outputs.hash }}
          message: ${{ steps.commit_title.outputs.title }}
          coder_session_token: ${{ secrets.CODER_SESSION_TOKEN }}
